### ISSUE TITLE
Upgrade ecotone/dbal to use latest doctrine/persistence

### ISSUE THREAD

**Issue by xNarkon** [ecotoneframework/ecotone-dev#111]
**Description**  
Currently on Symfony 6.2 there is an issue related to the doctrine/persistence. Symfony recommends to use the doctrine/persistence in the latest version 3+ to use of lazy ghost objects. Of course we can disable this feature for now to avoid the problems using a switch: enable_lazy_ghost_objects but it would be really nice to just upgrade dependencies in ecotone/dbal.

**Comment by dgafka** [comment]
Hello @xNarkon 

It's related to [enqueue/dbal](https://github.com/php-enqueue/dbal), it was not updated to `persistence version >= 3.0`.
Are you willing to help with this and provide PR in their [dev-repo](https://github.com/php-enqueue/enqueue-dev) that will bump the version?

**Comment by xNarkon** [comment]
@dgafka well, it's already in progress https://github.com/php-enqueue/enqueue-dev/pull/1290, could you push it a bit, as I can see you was a contributor? Thanks in advance!

**Comment by dgafka** [comment]
Thanks @jlabedo for updating that :)

**Comment by xNarkon** [comment]
@dgafka php-enqueue has already my changes merge

**Comment by dgafka** [comment]
cool @xNarkon, I think we don't need to update any package constraint on Ecotone side, right?
