### ISSUE TITLE
Add support of older versions of Doctrine/Dbal library

### ISSUE THREAD

**Issue by tworzenieweb** [ecotoneframework/ecotone-dev#175]
**Description**  
In order to provide wider support of this library for legacy projects, we should add support for legacy versions of `doctrine/dbal` library. In particular versions `^2.12.0|^3.0` have a bit different `QueryBuilder` methods available.

The other small changes are related to accessing the schema manager.

**Example**  
The implementation requires a proxy that will detect which version of QueryBuilder was provided. For the old one, it needs to add the missing shortcut fetch methods.

In order to not patch the doctrine code we need to provide a wrapper for query builder chain methods, providing the compatible base type but calling wrapped instance and extending with missing features.

**Comment by dgafka** [comment]
Solved with https://github.com/ecotoneframework/ecotone-dev/pull/176 https://github.com/ecotoneframework/ecotone-dev/pull/179
