### ISSUE TITLE
Acknowledge interceptor registered multiple times if multiple polling consumers are running

### ISSUE THREAD

**Issue by jlabedo** [ecotoneframework/ecotone-dev#229]
**Ecotone version(s) affected**: 1.108.1

**Description**  
The acknowledge interceptor is registered multiple times if multiple polling consumers are running

**How to reproduce**  
I did not manage to make a failing test, help would be welcome. If you run two polling consumers in the same messaging system, put a breakpoint on the `AcknowledgeConfirmationInterceptor::ack` method, the second polling consumer will be intercepted two times.

**Possible Solution**  
Fix the polling consumer builder.

**Comment by jlabedo** [comment]
Failing test added in #230

**Comment by dgafka** [comment]
Hey,
Solved with #233
