### ISSUE TITLE
reversion to 1.109.2 seems incomplete

### ISSUE THREAD

**Issue by m2mtech** [ecotoneframework/ecotone-dev#244]
**Ecotone version(s) affected**: 1.20x.y

**Description**  
Symfony 6.3 / PHP 8.2 / ecotone with event sourcing using symfony dbal crashes when updating

**How to reproduce**  
run `composer update` on project using Symfony 6.3 / PHP 8.2 with eventsourcing using symfony dbal

**Possible Solution**  
1.201.4 seems not a complete reversion to 1.109.2
https://github.com/ecotoneframework/symfony-bundle/compare/1.109.2...1.201.4

**Comment by dgafka** [comment]
Unfortunately yes, please use `1.109.2` in the meantime. 
Believe me, it's worth to wait ;)

**Comment by m2mtech** [comment]
Happy to wait ;)

**Comment by dgafka** [comment]
You should be up and running with [1.202.0](https://github.com/ecotoneframework/ecotone-dev/releases/tag/1.202.0) now :)

**Comment by m2mtech** [comment]
perfect, thanks
