### ISSUE TITLE
The symfony bundle is not compatible with Symfony 7

### ISSUE THREAD

**Issue by sktrendla** [ecotoneframework/ecotone-dev#286]
**Ecotone version(s) affected**: ^1.208

**Description**  

The Symfony bundle's classes are not fully compatible with the symfony 7 versions of their ancestors.
The tests do not run against specific Symfony version.

**How to reproduce**  

```bash
symfony new ecotone-example --version="7.0.*"
cd ecotone-example
composer require ecotone/symfony-bundle
```

**Context**  

For example:
> Compile Error: Declaration of Ecotone\SymfonyBundle\DepedencyInjection\Compiler\CacheWarmer::isOptional() must be compatible with Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerInterface::isOptional(): bool

The problem is not detected during testing because the *prefer stable* installation does not result in a full Symfony 7 installation.
For example during one of the latest test runs the *symfony/http-kernel* package resolves to a symfony 6 version as it is shown [here](https://github.com/ecotoneframework/ecotone-dev/actions/runs/7394525182/job/20116034501#step:6:177).

If composer install is run in the package's own subdirectory it currenty resolves the package used in the example to a Symfony 6 for the following reasons:
```bash
composer why symfony/http-kernel
```
> friends-of-behat/symfony-extension v2.4.2 requires  symfony/http-kernel (^4.4 || ^5.3 || ^6.0) 
> symfony/cache                      v7.0.2 conflicts symfony/http-kernel (<6.4)                 
> symfony/doctrine-bridge            v7.0.2 conflicts symfony/http-kernel (<6.4)      
> symfony/error-handler              v7.0.0 conflicts symfony/http-kernel (<6.4)                 
> symfony/framework-bundle           v7.0.2 requires  symfony/http-kernel (^6.4|^7.0)            
> symfony/messenger                  v7.0.1 conflicts symfony/http-kernel (<6.4)                 
>  symfony/translation                v7.0.2 conflicts symfony/http-kernel (<6.4)

**Comment by dgafka** [comment]
@lifinsky can you take a look?

**Comment by sktrendla** [comment]
The upgrade with prefer stable in the Symfony bundle's own sub-directory, currently no longer results in installation of Symfony 6 packages, because friends-of-behat/symfony-extension received Symfony 7 support with [v2.5.0](https://github.com/FriendsOfBehat/SymfonyExtension/releases/tag/v2.5.0).

**Comment by dgafka** [comment]
@sktrendla so it means we are good? :)

**Comment by sktrendla** [comment]
@dgafka No, the underlying problem of the incompatible types still exists. It's just possible to install the Symfony 7 versions of dependencyes for development purposes. I'll try to make a PR later today that fixes the type issues.

**Comment by sktrendla** [comment]
@dgafka I have succesfully tested the changes locally with the environment that is created by the script in the reproduction section, by specifying the local copy of the bundle as a path type repository and lowering the stability to dev. The steps for doing the same are the following assuming the PR's version is cloned:

```bash
symfony new ecotone-example --version="7.0.*"
cd ecotone-example
composer config minimum-stability dev
composer config repositories.foo path /path/to/symfony/bundles/sublfolder
composer require ecotone/symfony-bundle
```

**Comment by lifinsky** [comment]
I'll take a look and fix it tomorrow

**Comment by lifinsky** [comment]
Problem in dev dependency friends-of-behat/symfony-extension, I will fix it

**Comment by lifinsky** [comment]
https://github.com/FriendsOfBehat/SymfonyExtension/releases/tag/v2.5.0
I will also inspect all symfony module code

**Comment by lifinsky** [comment]
Also Laravel 10 still do not support Symfony 7 components
