### ISSUE TITLE
Converter services are not applicable for headers

### ISSUE THREAD

**Issue by lifinsky** [ecotoneframework/ecotone-dev#309]
**Ecotone version(s) affected**: 1.216.1

**Description**  
For example for test purpose I create value object TestUuid
```
final class TestUuid
{
    private function __construct(public readonly string $data) {
    }

    public static function fromString(string $data): self
    {
        return new self($data);
    }

    public function __toString(): string
    {
        return $this->data;
    }
}
```

And converter service:
```
class UuidConverter
{
    #[Converter]
    public function convert(string $source): TestUuid
    {
        return TestUuid::fromString($source);
    }
}
```

And send command:
```
$this->commandBus->sendWithRouting(
    'create.user',
    new CreateUser($name),
    metadata: ['userId' => '58009c9e-822d-4adb-906f-14c4bf9117e4']
);
```

And get an exception:
`Can't convert from application/json:string to application/x-php:App\Infrastructure\TestUuid Could not decode JSON, syntax error - malformed JSON.`

Converter class is not used because HeaderConverter thinks the headers are json media type.

Command handler:
```
#[CommandHandler('create.user')]
public static function register(CreateUser $command, #[Header('userId')] TestUuid $uuid): static
{
    return new static((string) $uuid, $command->user);
}
```

But if I create a media type converter, then everything works:
```
#[MediaTypeConverter]
class UuidConverter implements Converter
{
    public function convert($source, TypeDescriptor $sourceType, MediaType $sourceMediaType, TypeDescriptor $targetType, MediaType $targetMediaType): Test
    {
        return TestUuid::fromString($source);
    }

    /**
     * @inheritDoc
     */
    public function matches(TypeDescriptor $sourceType, MediaType $sourceMediaType, TypeDescriptor $targetType, MediaType $targetMediaType): bool
    {
        return $sourceType->isString() && $targetType->isClassOfType(TestUuid::class);
    }
}

```
Converter service works only for payload.

**How to reproduce**  
Use any value objects in headers except Ramsey\Uuid\UuidInterface (because UuidInterface in headers is supported by StringToUuidConverter)

**Possible Solution**  
HeaderConverter::getArgumentFrom method has a problem:
```
        if (! $sourceValueType->isCompatibleWith($targetType)) {
            if ($sourceValueType->isScalar() && $this->canConvertTo($headerValue, DefaultHeaderMapper::DEFAULT_HEADER_CONVERSION_MEDIA_TYPE, $targetType)) {
                $headerValue = $this->doConversion($headerValue, DefaultHeaderMapper::DEFAULT_HEADER_CONVERSION_MEDIA_TYPE, $targetType);
            } elseif ($this->canConvertTo($headerValue, MediaType::APPLICATION_X_PHP, $targetType)) {
                $headerValue = $this->doConversion($headerValue, MediaType::APPLICATION_X_PHP, $targetType);
            }
```
$this->canConvertTo($headerValue, DefaultHeaderMapper::DEFAULT_HEADER_CONVERSION_MEDIA_TYPE, $targetType))  returns true for json media type because only checks that just one converter exists (for real case - JmsConverter)

```
// AutoCollectionConversionService
    public function canConvert(Type $sourceType, MediaType $sourceMediaType, Type $targetType, MediaType $targetMediaType): bool
    {
        return (bool)$this->getConverter($sourceType, $sourceMediaType, $targetType, $targetMediaType);
    }
```
The second "if" would work, but code execution does not reach it:
`$headerValue = $this->doConversion($headerValue, MediaType::APPLICATION_X_PHP, $targetType);`

**Comment by dgafka** [comment]
True, it works like this. By default headers if are not scalars will be serialized and deserialized using json.  
I believe this was never exposed in documentation, was rather hidden gem :D. As documentation mention about keeping headers as simple types. 

But yea, we should rather serialize using PHP serialization and deserialization first, if possible and only then fallback to json.  
I will take a look on that :)

**Comment by lifinsky** [comment]
@dgafka VO is popular use case for headers, and this is not always uuid). It also seems to me a good practice to try to use converters for any deserialized types which, in principle, in this case are scalars and can be mapped to an object - it is also interesting to be able to map a Headers array to one VO.

**Comment by dgafka** [comment]
@lifinsky this should be solved with newest release: https://github.com/ecotoneframework/ecotone-dev/releases/tag/1.217.0

**Comment by dgafka** [comment]
Updated Docs:

https://docs.ecotone.tech/messaging/conversion/conversion/payload-conversion
https://docs.ecotone.tech/messaging/conversion/conversion/headers-conversion

**Comment by lifinsky** [comment]
Thanks!
