### ISSUE TITLE
Outbox

### ISSUE THREAD

**Issue by jlabedo** [ecotoneframework/ecotone-dev#31]
Hello Dariusz,

I am very impressed with Ecotone and what you achieved so far.

I think one of the missing piece for being totally production ready for my company is to have an implementation of the outbox pattern with distributed messaging.

With an outbox, asynchronous handlers and distributedBus would transactionaly save messages to the outbox table and an other process would publish messages recorded in the outbox in the real channel.

I would be glad to contribute on Ecotone but it is not easy to understand where I can safely implement this pattern. Maybe you already thought about it ?

**Comment by dgafka** [comment]
Hello @jlabedo,

Thank you for your kind words :) 

I am happy to tell you, that you may already use Ecotone with Outbox pattern: https://docs.ecotone.tech/modelling/asynchronous-handling#outbox-pattern.

I've added demo implementation for better overview.
Let me know, if that solves your use case :)

**Comment by jlabedo** [comment]
Thank you @dgafka for your quick reply and the documentation update !

My services are using different databases, so I guess I cannot share the same dbal backed channel between them (or I am missing something ?). My request was mostly to have an outbox (one per service) as you mentioned in the documentation, and then publish outbox messages to a central broker (rabbitmq).

**Comment by dgafka** [comment]
Each service would have it's own connection and channel.

Then publishing event to external service becomes part of your explicit asynchronous flow within given service.

```php
#[Asynchronous("async")]
#[EventHandler(endpointId:"publishPublicEvent")]
public function publishPublicEvent(OrderWasPlaced $event) : void
{
    // publish it to external service
}
```

In case you want to use [Distributed Bus](https://docs.ecotone.tech/modelling/microservices-php#distribution-bus)

```php
#[Asynchronous("async")]
#[EventHandler(endpointId:"publishPublicEvent")]
public function publishPublicEvent(OrderWasPlaced $event,, DistributedBus $distributedBus) : void
{
    $distributedBus->convertAndPublishEvent("order_was_placed", $event);
}
```

**Comment by dgafka** [comment]
You may have single method for this, as in order to subscribe to multiple events you can use union types.

```php
#[Asynchronous("async")]
#[EventHandler(endpointId:"publishPublicEvent")]
public function publishPublicEvent(OrderWasPlaced|OrderWasCancelled|OrderWasDelivered $event) : void
{
    // publish it to external service
}
```

**Comment by jlabedo** [comment]
Well, that should work! Now I don't get how I did not thought on this flow by myself... :)

Many thanks for your help!

**Comment by dgafka** [comment]
Glad I could help, have fun with Ecotone :)

**Comment by dgafka** [comment]
@jlabedo new article may be helpful in case of integrating microservices together using Ecotone: https://dariuszgafka.medium.com/loosely-coupled-microservices-in-php-130699e80344
