### ISSUE TITLE
Combined channel for outbox: DB -> distributed publisher

### ISSUE THREAD

**Issue by lifinsky** [ecotoneframework/ecotone-dev#313]
**Description**  
Sending a command to another microservice should also be guaranteed through the outbox pattern. It is currently not possible to combine these channels through a combined channel. Currently there are 3 stages: db consumer -> async (internal consumer) -> publisher (new message to distributed bus exchange).

**Example** 
Service configuration for async outbox
```
    #[ServiceContext]
    public function enableRabbitMq(): AmqpBackedMessageChannelBuilder
    {
        return AmqpBackedMessageChannelBuilder::create('internal');
    }

    #[ServiceContext]
    public function databaseChannel(): DbalBackedMessageChannelBuilder
    {
        return DbalBackedMessageChannelBuilder::create('db');
    }

    #[ServiceContext]
    public function combinedMessageChannel(): CombinedMessageChannel
    {
        return CombinedMessageChannel::create(
            'outbox',
            ['db', 'internal'],
        );
    }
```

Distributed bus publisher:
```
    #[EventHandler(endpointId: 'order.changed')]
    #[Asynchronous('outbox')]
    public function changeBillingDetails(OrderChanged $event, DistributedBus $distributedBus): void
    {
        $distributedBus->sendCommand(
            'billing',
            'billing.changeDetails',
            '["personId":"123","billingDetails":"01111"]',
            'application/json',
        );
    }
```

Is it possible to make sending a command to a db channel with automatic sending to the distributed channel (combined channel between db and distributed), skipping sending OrderChanged to async internal channel? For example:

```
$distributedBus->sendCommand(
  'billing_outbox', // combined channel db -> distributed publisher channel to billing service using Ecotone service configuration
  'billing.changeDetails',
  '["personId":"123","billingDetails":"01111"]',
  'application/json',
);
```

**Comment by dgafka** [comment]
@lifinsky have you found current solution, solving your problem?

**Comment by lifinsky** [comment]
Hi. We will use db channel for this. 
Can you tell me if delayed retries will work with a distributed event or command handler?

https://docs.ecotone.tech/modelling/recovering-tracing-and-monitoring/resiliency/retries

In documentation I see examples for async endpoints.

**Comment by lifinsky** [comment]
How to use custom delayed strategy for distributed consumer?
