### ISSUE TITLE
Synchronous event handlers order or priority

### ISSUE THREAD

**Issue by lifinsky** [ecotoneframework/ecotone-dev#325]
**Description**  
Currently, event handler priority works only for asynchronous event handlers. However, to ensure that, for example, one of the projections is processed first, it is necessary to have the ability to prioritize the event handler.

**Comment by lifinsky** [comment]
There is an event-sourcing transaction aggregate and an event-sourcing customer balance aggregate. To create a projection of fund movements on the balance, we need up-to-date transaction data. Ideally, to avoid using event handler prioritization, it would be great to guarantee that the synchronous projection is executed immediately after the event is saved to its aggregate in the event store, and only after that, the event is listened to by another aggregate.

**Comment by dgafka** [comment]
Hey @lifinsky,

Yep, priority does work only for async, but I don't see reason why wouldn't it work for sync scenarios too. 
I will see what we can do with it when I will have some free time :)

**Comment by dgafka** [comment]
This feature is now added https://github.com/ecotoneframework/ecotone-dev/releases/tag/1.223.0
