### ISSUE TITLE
Symfony - Ecotone Dbal - non-existent service "Enqueue\Dbal\DbalConnectionFactory"

### ISSUE THREAD

**Issue by galliroberto** [ecotoneframework/ecotone-dev#378]
**Ecotone version(s) affected**:
ecotone-dbal: 1.231.0
ecotone/symfony-bundle: 1.231.0

**Description**  
I have install ecotone and ecotone/dbal in symfony.
I have added to a bundle
```php
<?php 

return [
    Ecotone\SymfonyBundle\EcotoneSymfonyBundle::class => ['all' => true],
];
```

I get:
```
The service "Ecotone\Dbal\ObjectManager\ObjectManagerInterceptor" has a dependency on a non-existent service "Enqueue\Dbal\DbalConnectionFactory". Did you mean one of these: "Ecotone\Dbal\Recoverability\DbalDeadLetterHandler.Enqueue\Dbal\DbalConnectionFactory", "Ecotone\Dbal\DocumentStore\DbalDocumentStore.Enqueue\Dbal\DbalConnectionFactory"?
```

**How to reproduce**  
Symfony version: 6.4
ecotone-dbal: 1.231.0
ecotone/symfony-bundle: 1.231.0

Run in web browser or clean cache

**Comment by lifinsky** [comment]
Hi
https://docs.ecotone.tech/modules/symfony/symfony-database-connection-dbal-module

If we don't have existing connection defined, we can make use of DSN directly

```
Enqueue\Dbal\DbalConnectionFactory:
   class: Enqueue\Dbal\DbalConnectionFactory
   factory: ["Ecotone\Dbal\DbalConnection", "fromDsn"]
   arguments: ["pgsql://user:password@host:5432/db_name"]
```

**Comment by galliroberto** [comment]
Thank you!
