### ISSUE TITLE
ClassNotFoundError thrown when excluding files from composer classmap

### ISSUE THREAD

**Issue by jlabedo** [ecotoneframework/ecotone-dev#382]
**Ecotone version(s) affected**: 1.231.1

**Description**  
I have a directory structure where some tests are located in the same namespace as production code, like Symfony does in its monorepo (for instance [this test](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Serializer/Tests/DeserializeNestedArrayOfObjectsTest.php)).
When building without composer dev packages (`--no-dev`), Ecotone will parse the test file and throw a ClassNotFound error because of missing PHPUnit required by the test file.

**How to reproduce**  
Include a test case inside the `src` directory, run `composer install --no-dev` with a **valid** composer.json file:
```json
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        },
        "exclude-from-classmap": [
            "**/Tests/",
            "**/bin/"
        ]
    },
```

**Possible Solution**  
- Ignore unreadable classes when parsing annotations.
- Read "exclude-from-classmap" to exclude it from annotations finder

**Comment by dgafka** [comment]
> Read "exclude-from-classmap" to exclude it from annotations finder

That sounds more resilient, as ignoring could hide real issues.
