### ISSUE TITLE
EcotoneLite::bootstrapFlowTesting not updating attributes from filesystem

### ISSUE THREAD

**Issue by jlabedo** [ecotoneframework/ecotone-dev#395]
**Ecotone version(s) affected**: 1.231.4

**Description**  
When using `EcotoneLite::bootstrapFlowTesting`, the cache is always used when using `ServiceConfiguration::withNamespaces()`, making tests very hard to debug :)

**How to reproduce**  
In this test, the namespace attributes will be automatically cached:
```php
EcotoneLite::bootstrapFlowTesting(
            configuration: ServiceConfiguration::createWithDefaults()
                ->withNamespaces(["App\MyDomain"])
)
```

When using "classes to resolve" parameter, attributes are correctly updated:
```php
EcotoneLite::bootstrapFlowTesting(['App\MyDomain\ClassA', 'App\MyDomain\ClassB'])
```

**Possible Solution**  
This seems to come from this piece of code:
https://github.com/ecotoneframework/ecotone-dev/blob/13ec84e586a1a606358af47e5b80cb49eb7ec570/packages/Ecotone/src/Lite/EcotoneLite.php#L378-L383

**Comment by lifinsky** [comment]
We even always clear the runtime cache before running integration tests

**Comment by jlabedo** [comment]
Yeah, I might have missed the last part of the documentation https://docs.ecotone.tech/modelling/testing-support/testing-messaging#caching-configuration

But It does not seems very DX friendly, especially when you write your tests first

**Comment by dgafka** [comment]
@jlabedo hmm if it does not update, it's a bug. 

We would need to re-evaluate files collected from that namespace, because indeed that's not expected behaviour
