### ISSUE TITLE
Invalid ecotone/pdo-event-sourcing package dependency version

### ISSUE THREAD

**Issue by lifinsky** [ecotoneframework/ecotone-dev#396]
**Ecotone version(s) affected**: 1.233.0

**Description**  
ecotone/pdo-event-sourcing package has dependency ecotone/dbal version 1.232.1 instead of 1.233.0

**Context**  
https://github.com/ecotoneframework/pdo-event-sourcing/blob/1.233.0/composer.json#L36

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires ecotone/pdo-event-sourcing 1.233.* -> satisfiable by ecotone/pdo-event-sourcing[1.233.0].
    - ecotone/pdo-event-sourcing 1.233.0 requires ecotone/dbal ~1.232.1 -> found ecotone/dbal[1.232.1] but it conflicts with your root composer.json require (1.233.*).
```

**Comment by lifinsky** [comment]
@dgafka could you please update and publish all ecotone packages up to version 1.233.0 or 1.233.1 (with my last fix for sync retry configuration)

**Comment by lifinsky** [comment]
Also latest version Ecotone Symfony bundle is not actual: https://github.com/ecotoneframework/symfony-bundle/blob/1.233.0/DependencyInjection/EcotoneExtension.php#L28

Missing:
`$config = $container->resolveEnvPlaceholders($config, true);`

**Comment by dgafka** [comment]
There is a bug with package splitting, which fails when there is an `(` in the comment.
https://github.com/ecotoneframework/ecotone-dev/actions/runs/11392249084/job/31698035781

This as a result does not release correctly.
https://github.com/danharrin/monorepo-split-github-action/issues/42

If know how this can be fixed, happy to approve PR.
Release new version in the meantime :)
