### ISSUE TITLE
SIGTERM, SIGINT doesn't work with AMQP consumers

### ISSUE THREAD

**Issue by lifinsky** [ecotoneframework/ecotone-dev#410]
**Ecotone version(s) affected**: latest

**Description**  
The consumer process cannot be terminated correctly with AMQP channel.

**How to reproduce**  
```
php bin/console ecotone:run async &
```
Run `ps` and find process pid
```
kill -s SIGTERM <pid>
```

The process will not stopped. At the same time, everything works correctly with db consumer.

**Comment by lifinsky** [comment]
@dgafka Hi)

**Comment by lifinsky** [comment]
A bit of debugging in InterceptedConsumer
```
while ($this->shouldBeRunning()) {
            \var_dump('--run--');
```

```
private function shouldBeRunning(): bool
    {
        if (! $this->shouldBeRunning) {
            return false;
        }

        foreach ($this->consumerInterceptors as $consumerInterceptor) {
            if ($consumerInterceptor->shouldBeStopped()) {
                \var_dump('--should be stopped--');
```


```
php bin/console ecotone:run db
string(7) "--run--"
string(7) "--run--"
^Cstring(21) "--should be stopped--"
```

```
php bin/console ecotone:run async
string(7) "--run--"
string(7) "--run--"
^Cstring(7) "--run--"
string(7) "--run--"
```

**Comment by lifinsky** [comment]
Interceptors list:

Ecotone\Messaging\Endpoint\Interceptor\LimitMemoryUsageInterceptor
Ecotone\Messaging\Endpoint\Interceptor\SignalInterceptor
Ecotone\Messaging\Endpoint\Interceptor\ConnectionExceptionRetryInterceptor

**Comment by lifinsky** [comment]
@dgafka `$extQueue->consume(function (\AMQPEnvelope $extEnvelope, \AMQPQueue $q)` leads to this problem

**Comment by lifinsky** [comment]
https://github.com/php-enqueue/enqueue-dev/issues/332

**Comment by lifinsky** [comment]
Possible solution: inherit from AmqpSubscriptionConsumer and replace the `$extQueue->consume` call with the code below:

```php
            for (;;) {
                $extEnvelope = $extQueue->get();
                if (!$extEnvelope) {
                    usleep(100000);
                    return;
                }

                $message = $this->context->convertMessage($extEnvelope);
                $message->setConsumerTag($q->getConsumerTag());

                /**
                 * @var AmqpConsumer
                 * @var callable     $callback
                 */
                list($consumer, $callback) = $this->subscribers[$q->getConsumerTag()];

                call_user_func($callback, $message, $consumer);
            }
```

**Comment by lifinsky** [comment]
I have a problem after the new implementation with only the test `test_distributing_command_misses_heartbeat_and_reconnects`

**Comment by lifinsky** [comment]
@dgafka I can create PR

**Comment by dgafka** [comment]
@lifinsky there is difference in `basic_consume` and `basic_get` and resulting performance. 
Basic consume will do better than calling basic_get, and it does work with RabbitMQ streams (where get, does not).

So switching to get should rather be considered as last sort of effort. 
I may take a look if I can find any solution but not sure when I will find time for that. 
So if you can take a look and search for one that would be great

**Comment by lifinsky** [comment]
Consume cannot be used, it blocks signals. And without the ability to correctly terminate the process, the current solution makes no sense.

**Comment by dgafka** [comment]
Process is running
![image](https://github.com/user-attachments/assets/43c24ccd-96a8-4b71-bdbf-04c4c6fd7997)
After killing, process is stopped
![image](https://github.com/user-attachments/assets/42ea70db-84a2-4e9b-968f-97b3d2600379)

I could kill the process by sending an signal in newest version for Ecotone.
Are you sure, there is a problem?

**Comment by lifinsky** [comment]
Yes, I am sure. Consume calback + read timeout blocks signals. You can test it with empty queue for example.
