### ISSUE TITLE
Inheritance support for Aggregates

### ISSUE THREAD

**Issue by CipherdevNL** [ecotoneframework/ecotone-dev#89]
**Ecotone version(s) affected**: 1.74

**Description**  
For a project we've some processes/ event flows that are similar between two different concepts. To prevent drift in the process (e.g. AggregateA behaves different than AggregateB) we wanted to use inheritance on those aggregates.

This way we can keep the core data/ flow of those processes the same and reuse the handlers and extend the behaviour inside the child aggregates. 

In the first try we encountered the following error:
```
$ bin/console c:c

Channel name `Project\CommandX` should be unique, but is used in multiple handlers: Project\AggregateA:handleX Project\AggregateB:handleX Project\BaseAggregate:handleX
```

After digging through the code we found the following attribute `#[NotUniqueHandler]` that was able to solve this error, but after applying it another error popped up:

```
$ bin/console c:c

You have requested a non-existent service "Project\BaseAggregate".
```

Most likely this problem occurs as Ecotone tries to create a channel for the handler it found on the abstract base class. But failed as such classes are not existing in the service container. By manually patching some central place in the code I was able to get rit of the message and have a working inheritance setup.

The patch that we applied is to filter out all the abstract classes from the result that the `FileSystemAnnotationFinder.php` is giving. But I'm aware that this patch is far from ideal as it's leaking Ecotone concerns into the AnnotationFinder part of the framework. But I'm not that familiar with the codebase to know which patches must be applied inside the Ecotone part to exclude non-constructible classes from getting into the CommandHandler preparation part.

This is the dirty patch in `FileSystemAnnotationFinder.php` I created so far to continue the development of the project:
```php
    private function init(string $rootProjectDir, array $namespacesToUse, string $catalogToLoad, AutoloadNamespaceParser $autoloadNamespaceParser, array $systemClassesToRegister, array $userClassesToRegister, bool $isRunningForTesting)
    {
        if (! $catalogToLoad && $namespacesToUse == [] && $userClassesToRegister == [] && ! $isRunningForTesting) {
            throw ConfigurationException::create('Loading catalog was turned off and no namespaces were provided. Please provide namespaces manually via configuration or turn on catalog loading. Read related Module section at https://docs.ecotone.tech');
        }

        $registeredClasses = array_merge($systemClassesToRegister, $userClassesToRegister);
        if ($catalogToLoad) {
            $registeredClasses = array_merge(
                $registeredClasses,
                $this->getClassesIn([$rootProjectDir . DIRECTORY_SEPARATOR . $catalogToLoad], null)
            );
        }

        $registeredClasses = array_merge(
            $registeredClasses,
            $this->getRegisteredClassesForNamespaces($rootProjectDir, $autoloadNamespaceParser, $namespacesToUse)
        );

        $this->registeredClasses = array_unique($registeredClasses);

        // START PATCH
        $this->registeredClasses = array_filter(
            $registeredClasses,
            static function (string $className) {
                $ref = new \ReflectionClass($className);

                return ! $ref->isAbstract() || $ref->isInterface();
            }
        );
        // END PATCH
    }
```

**How to reproduce**  
```php
abstract class BaseAggregate
{
    use WithAggregateEvents;

    #[AggregateIdentifier]
    public Uuid $id;

    #[AggregateVersion]
    protected int $version = 0;

    #[NotUniqueHandler]
    #[CommandHandler]
    public function handleX(CommandX $command): void
    {
        $this->recordThat(PerformedX::raise($this->id));
    }
    
    #[NotUniqueHandler]
    #[EventSourcingHandler]
    public function onPerformedX(PerformedX $event): void
    {
        var_dump("performed");
    }
}
```

```php
#[EventSourcingAggregate(true)] 
class AggregateA extends BaseAggregate
{
    #[CommandHandler]
    public static function create(CreateAggregateA $command): self
    {
        $instance = new self();
        $instance->recordThat(CreatedAggregateA::raise($command->id));

        return $instance;
    }
}
```

```php
#[EventSourcingAggregate(true)] 
class AggregateB extends BaseAggregate
{
    #[CommandHandler]
    public static function create(CreateAggregateB $command): self
    {
        $instance = new self();
        $instance->recordThat(CreatedAggregateB::raise($command->id));

        return $instance;
    }
}
```

After having those aggregates in place perform a symfony cache clear
```bash
bin/console c:c
```

**Possible Solution**  
Filtering out non-constructible classes while creating channels for the different handlers.

**Context**  
It was some time ago I encountered and fixed this issue locally so I don't know the great details anymore.
But if you need more (detailed) information, feel free to let me know and I will refresh my memory.

Also thanks for this amazing Event Sourcing framework! I really love using it :)

**Comment by dgafka** [comment]
Hey @CipherdevNL

I see you've digged out the hidden feature of `#[NotUniqueHandler]`. That was not meant to be part of public interface :D

Before I will propose anything, let me understand the context :)   

The way `NotUniqueHandler` works is that it will allow to `pub-sub` commands, so in your case, when you send the command, it will first execute `handleX` on `AggregateA` and then `handleX` on `AggregateB`.  
Is this is what you're trying to achieve?

**Comment by CipherdevNL** [comment]
Oops, sorry for that 😅  but good to know it wasn't ment to be used outside the framework, so I know this can be break down the road.

Hmm, that's not really what I try to achieve, but maybe due to usage of different (unique) identifiers between AggregateA and AggregateB this won't be a real issue for me? What I really want to achieve is that commands with a `TargetAggregateIdentifier` for an `AggregateA` instance only gets applied to `AggregateA` and not on `AggregateB`. This all while extending from a base aggregate class that contains the handlers (and logic) of those events & commands. And ofc this should also be the case vice versa :).

Tbh. the project I'm working on only has the core domain implemented and covered with Unit Tests, so I've not field tested if there is no runtime conflict between those Aggregates and Handlers.

Hope this gives some context on what I want to achieve :). If you want I can also briefly go into the exact usecase for the project, but don't want to bother you with domain specific information.

**Comment by dgafka** [comment]
I've provided support for skipping abstract classes with #90 :) 

About multiple Command Handlers with same Command.  
Command Handlers are meant to target single endpoint, as otherwise Command starts to work like Events in a `pub-sub` way. On single `Service` level it's not a such a problem, yet when there are multiple `Services` and they would subscribe to same Command, you can imagine that this requires different integration. 

In my previous work however, we had used `NotUniqueHandler` to bypass this, as we wanted to update two or three aggregates during registration in same `Service`. So it's possible solution yet not something to be promoted, as it has it's drawbacks ;)  

Your use case is different tho, as you want to target specific aggregate, yet route the Message not based on `Command Class`, but `Aggregate Identifier`.   
I would say just copy/paste the logic and let the aggregates be isolated from each other. And if you're really want to do it, share the logic but expose different Commands, so it's clear which aggregate we are targeting. 
If you don't want to create different Command Class, just make use of [Routing](https://docs.ecotone.tech/modelling/command-handling/command-dispatching#send-with-routing) :)

That being said, if you still want to do it this way, then you can bypass the limitation using `NotUniqueHandler`. This will actually run two Command Handlers and expect aggregate to be there, so you would need to set `dropMessageOnNotFound: true`, this will skip calling aggregate if it not exists.

```php
    #[NotUniqueHandler]
    #[CommandHandler(dropMessageOnNotFound: true)]
    public function handleX(CommandX $command): void
    {
        $this->recordThat(PerformedX::raise($this->id));
    }
```

This solution has two drawbacks, now whenever you will send `CommandX`, it will try to load both of the aggregates. So for each command, you will pay extra hit do database.  
Secondly, if you will have a bug and identifier will be incorrect it will not find any of those aggregate, yet your system will not warn you, because we are dropping those messages.  

Let me know, if this explain the subject in depth and solves your problem :)

**Comment by CipherdevNL** [comment]
Thanks for the quick response and actions on this!

How you explain it with the drawbacks it comes with makes it clear, the extra database hit wouldn't be that much of a problem as the system will not get a huge amount of traffic, so we can handle that penalty. The second drawback you mention might be more concerning as that could have problematic consequences when it goes wrong, good for pointing that out!

As I understand correctly, by using the Routing approach most/ all of those drawbacks can be resolved. This would be an interesting alternative approach worth looking into, but have to see how to elegantly implement it into the codebase by reducing the amount of manually defined routing key for each aggregate.

For now this will answer my problem and gives some insight in potential drawback down the road. I'm planning on testing it out, but I don't know when that will be. Think you can consider this problem as resolved, when I encounter problems during implementation I will try to figure it out and reopen the issue :).

**Comment by dgafka** [comment]
@CipherdevNL sure, happy to help :)
